### ISSUE TITLE
pattern3.db import CSV throws OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by Code4SAFrankie** [pattern3/pattern#45]
from pattern3.db import CSV

throws the error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\pattern3\db\__init__.py", line 2159, in <module>
    csvlib.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

on 

WinPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

**Comment by Code4SAFrankie** [comment]
Not sure what the line `csvlib.field_size_limit(sys.maxsize)` is doing there. I just commented it and then `from pattern3.db import CSV` worked fine. Not sure if the comment will cause other issues though.
