### ISSUE TITLE
from pattern3.search import search throws IndentationError: expected an indented block error

### ISSUE THREAD

**Issue by Code4SAFrankie** [pattern3/pattern#46]
from pattern3.search import search

throws the error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\pattern3\text\search.py", line 273
    except ImportError:
         ^
IndentationError: expected an indented block

on

WinPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

and on

Ubuntu 
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

**Comment by Code4SAFrankie** [comment]
Seems to be due to an empty try block:

    def itervalues(self):
        try:
            
        except ImportError:
            imap = map
        return map(self.__getitem__, reversed(self._o))
